IntersectMBO/governance-actions

README.md
sanchonet/2024-10-21-ppu-cost-model/README.md
sanchonet/2024-10-21-ppu-cost-model/metadata.jsonld
sanchonet/2024-10-21-ppu-cost-model/metadata.jsonld.md

- Add rough template
- [related issue](https://github.com/IntersectMBO/xxxx/issues/)

sketch what template could look like

---

README.md
preprod/2024-10-21-ppu-cost-model/README.md
preprod/2024-10-21-ppu-cost-model/metadata.jsonld
preprod/2024-10-21-ppu-cost-model/metadata.jsonld.md
sanchonet/2024-10-21-ppu-cost-model/README.md

- Created Directory for PreProd Governance Action MetaData

Created PreProd and Mainnet Gov Action Metadata for Plutus v3 Cost Model Parameter Change in Protocol v10 (Chang#2)

---

README.md
mainnet/2024-10-21-ppu-cost-model/README.md
mainnet/2024-10-21-ppu-cost-model/metadata.jsonld
preprod/2024-10-21-ppu-cost-model/README.md
preprod/2024-10-21-ppu-cost-model/metadata.jsonld
sanchonet/2024-10-21-ppu-cost-model/README.md
sanchonet/2024-10-21-ppu-cost-model/metadata.jsonld

- Change JSONLD formatting, to be neater
- Fix link to raw metadata files

Change: tidy metadata documents

---

mainnet/2024-10-21-ppu/README.md
preprod/2024-10-21-ppu/README.md
preview/2024-10-21-ppu/README.md

fix broken links throughout

---

preview/2024-10-21-ppu/README.md

fix preview link typo

---

preprod/2024-10-21-ppu/README.md
preview/2024-10-21-ppu/README.md

- Add links to PlutusV3 cost model PPU transactions

add transaction links for cost model ppu on testnets

---

mainnet/2024-10-21-ppu/README.md
mainnet/2024-10-21-ppu/metadata.jsonld

- Add english language property to mainnet ppu metadata

add: english language property to mainnet ppu metadata

---

preview/2024-10-30-hf10/README.md
preview/2024-10-30-hf10/metadata.jsonld

- Add language property to preview hf10 metadata

add language property to preview hf10 metadata

---

mainnet/2024-10-21-ppu/metadata.jsonld

- Add TSC meeting minutes link to references

add TSC meeting minutes

---

mainnet/2024-10-21-ppu/README.md
mainnet/2024-10-21-ppu/metadata.jsonld
mainnet/2024-10-21-ppu/metadata.jsonld.md
preview/2024-10-30-hf10/README.md

- Fix hashes for preview hf and mainnet ppu

Fix hash and spelling mistake for mainnet ppu and hash for preview hardfork

---

README.md

- add preview hf to base repo readme

docs: add preview hf to base repo readme

---

preprod/2024-10-30-hf10/README.md

- add hash for preprod hf action

add hash for preprod hf action

---

preprod/2024-10-30-hf10/README.md

- Add Preprod 10.0 HF action transaction ID

Add Preprod 10.0 HF action transaction ID

---

mainnet/2024-11-19-infohf/README.md
mainnet/2024-11-19-infohf/metadata.jsonld
mainnet/2024-11-19-infohf/metadata.jsonld.md

- Add placeholder for Plomin info action metadata

sketch out dir for Plomin hf info action

---

mainnet/2024-11-19-infohf/metadata.jsonld

- Update rationale for Plomin Hard Fork info action

Update rationale content for Plomin Hard Fork

---

README.md
mainnet/2024-11-19-infohf/README.md
mainnet/2024-11-19-infohf/metadata.jsonld.md

- Add supporting files for Plomin fork generate from scripts

add supporting files for Plomin fork

---

mainnet/2024-10-21-ppu-x/README.md
mainnet/2024-11-04-ppu/README.md
mainnet/2024-11-19-infohf/README.md

- add links to block explorers for submitted transactions

add links to block explorers for submitted transactions

---

mainnet/2024-10-30-hf10/README.md

- Fix: JSON file check command

fix: JSON file check command

---

mainnet/2024-10-30-hf10/README.md

- add blockexplorer links for mainnet hf

add blockexplorer links for mainnet hf

---

preview/2025-01-23-const/README.md
preview/2025-01-23-const/metadata.jsonld
preview/2025-01-23-const/metadata.jsonld.md

- Change new constitution metadata as per 01-23

redo metadata for 01-23

---

preview/2025-01-23-const/README.md

New const iterations

---

mainnet/2025-01-30-const/README.md

add transaction id references for new constitution action

---

ratification-queries/info-ratification.sql

init info action ratification query

---

mainnet/2025-02-27-inforoadmap/README.md
mainnet/2025-02-27-inforoadmap/metadata.jsonld
mainnet/2025-02-27-inforoadmap/metadata.jsonld.md

init roadmap info action

---

README.md

update base readme with roadmap info action

---

ratification-queries/info-ratification.sql
ratification-queries/ratification-methodology.md

restructure and add more comments

---

ratification-queries/info-ratification-historical.sql

add historical attempt

---

ratification-queries/info-ratification.sql

tidy equation and add note

---

README.md
mainnet/2025-05-12-infobudget/README.md

add on-chain links

---

preprod/2025-04-23-tw/README.md
preprod/2025-04-23-tw/metadata.jsonld
preprod/2025-04-23-tw/metadata.jsonld.md

Add new treasury withdrawal GA on preprod

---

scripts/create-human-readable-from-json.sh
scripts/validate-json.sh

feat: add basic validation script

---

scripts/validate-budget-metadata.sh

- #81 
takes a directory
for each .jsonld
- run normal validation script
- run author validation script
- run custom validations for Intersect treasury withdrawals

[WIP] feat: budget validation script

---

schemas/treasury-withdrawal/common.jsonld
schemas/treasury-withdrawal/specification.md

refine spec, add return address and withdrawal object

---

schemas/treasury-withdrawals/common.jsonld
schemas/treasury-withdrawals/example.json

Fix context in Intersect schema

---

schemas/treasury-withdrawals/examples/README.md
schemas/treasury-withdrawals/examples/incorrect-author-example.json
schemas/treasury-withdrawals/examples/many-withdrawals.json

- Add more treasury schema examples

add more treasury schema examples

---

schemas/treasury-withdrawals/common.schema.json

update schema to force author

---

schemas/treasury-withdrawals/common.schema.json

improve schema

---

mainnet/2025-07-24-uc-2025/README.md

add links to explorers

---

schemas/info/common.schema.json

remove withdrawals field property for info actions
